export const GameLinks = {
    "Baccarat": "/bitcoin-baccarat",
    "Blackjack": "/blackjack-bitcoin-casino",
    "Crash": "/crash-crypto-game",
    "Dice": "/dice-bitcoin-casino",
    "Jackpots": "/bitcoin-jackpot",
    "Keno": "/keno-bitcoin",
    "Live Casino": "/bitcoin-live-casino",
    "Lottery": "/lottery-bitcoin-sites",
    "Plinko": "/plinko-casino",
    "Poker": "/bitcoin-poker-sites",
    "Roulette": "/roulette-bitcoin-casino",
    "Sic Bo": "/sic-bo-bitcoin",
    "Slots": "/slots-bitcoin-casino",
    "Sports Betting": "/bitcoin-sports-betting",
}